### ISSUE TITLE
UI: Enhancing preferences menu to 4 pages and bugs to be fixed

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#146]
The Preferences menu already was changed due to prior commits from 2 sections layout ("more" button) to 3 sections layout "HUD", "Chat" and "Help" with additional options. Some of the original options there were moved to Setup / Display because they can influence the fps. But also this menu is getting rather full with more options to come there. That's why it is better to keep them in the Preferences menu.

### ToDo
- [x] New graphics GAME (on/off) for a new section Game
- [x] Add a new section Game according to HUD", "Chat" and "Help". Game should be second menu page
- [x] Transfer formerly moved options back from Display to the new Game section
- [x] Move player model related options from HUD to Game section (force model, glowing model and glow color)
- [x] Add indicate health option as new entry to HUD section to enable the crosshair to indicate the player's health
- [x] Fix: Sync every frame has nothing to do with VSYNC. tooltip needs to be corrected and to explain this
- [x] Fix: Default value of team overlay. WoP only knows 0/1 and not 4. That's why the team overlay option was always shown as disabled when switching back to defaults.
- [x] Enable flares by default
- [x] Add useful tool tips to all option on the menu page
- [x] Fix: Ingame video option not working (see 4)
- [x] Fix: Glow model option always shown as off (see 1)
- [x] Investigate the faulty or not working behavior of icons (see 3 and 4)

### Things I discovered when testing my code changes:

1. ~~After I did the code changes it doesn't matter which color is selected, the radio button is always turned off after revisiting the menu. I cannot see which of my changes caused this.~~

2. Somehow the wallhack icons options doesn't seem to work any more. I can enable all icons in the menu but none of them are shown to me when the conditions are reached when they should be enabled e.g. health below 50% or a collected cartridge. So something is wrong with the cg_icons cvar handling. The menu options in fact change the value of cg_icons. Also i realized that the teammate icon is enabled/disabled by cg_drawfriend, which simply draws the PAD logo over the players heads, but it neither is visible through walls nor is it changing the size due to changing the distance.

3. ~~Also the freeze tag icon has the same behavior like the teammate icon. The menu option enabling/disabling it has no effect and it neither is visible through walls nor is it changing the size due to changing the distance. We need to investigate here.~~

4. ~~The new menu option to enable/disable Ingame Videos seems not to have an effect, but when I set the cvar r_inGameVideo directly via console it takes effect immediately and works properly. This is strange and I cannot see why.~~

**Comment by 3aTmE** [comment]
The "Indicate Health" Button from the H.U.D. menu won't work with any Crosshairs. 
checked the console if the game set `/cg_crosshairHealth` to `1`. 

It did not. 

Had to enable it by hand in the Console. 
Tried to disable it again from the menu but that change also won't apply.  

Like mentioned above the freeze tag icon still has issues. While it is visible through walls with the current Codebase it still _won't_ scale :
![shot0000](https://user-images.githubusercontent.com/84514074/165895449-b97c77df-5c03-412a-b299-f0328bc520a7.jpg)

Everything else seems to work like it should.

**Comment by kai-li-wop** [comment]
Thx for reporting the issue. Should be fixed now.

**Comment by 3aTmE** [comment]
> Thx for reporting the issue. Should be fixed now.

NP, just tested it.
Can Confrim the fix :) 

"Indicate Health" works now!

€: The Freeze Tag Icon behaves quite odd.
Sometimes i am able to see it through the Enviroment, sometimes not. 
Are Structural brushes the ones blocking the display of the icons?
In the screenshot above the lava lamp is completly made of curves and as you can see you are able to see the icon.

**Comment by kai-li-wop** [comment]
Apart from the freezetag icon I think something broke due to changes made here #59. So we need to investigate the issue, which is probably not related to the menu. I will close this ticket and will address the issues there or in a new issue ticket. Thx for your help! Most welcome!
