### ISSUE TITLE
Restore and adjust Q3A defense medal as 'PadHero' in WoP

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#15]
Icon | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_excellent.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_snackattack.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_padstar_blue.png" width="60" /> <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_padstar_red.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_padhero.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_padace.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_spraykiller.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_spraygod.png" width="60" />
--- | :---: | :---: | :---: | :---: | :---: | :---: | :---:
Name | Excellent | SnackAttack | PadStar (BLUE/RED) | PadHero | PadAce | SprayKiller | SprayGod

## Tasks

- [x] Restore the Defense award behavior from vanilla Q3 for the game mode Capture The Lolly. It should be awarded for defending the base and the lolly carrier by taking out enemy players/bots near your lolly or near the team member currently carrying the lolly (1000 units).
- [x] Apply the Defense award also to the game mode Big Balloon. It should be awarded for defending a balloon box in your own team color by eliminating opponents in the boxes vicinity (1000 units).
- [x] Apply the Defense award also to the game mode Spray Your Color Team. It should be awarded for defending a team mate carrying min 5 cartridges by eliminating opponents in the team mates vicinity (1000 units).
- [x] Needs an icon texture plus shader
- [ ] Needs an announcer sound file

**Comment by kai-li-wop** [comment]
Tasks
- [ ] Award the PadStar medal (capture award) instead of a colored balloon HUD icon In the game mode Big Balloon
- [ ] Restore the Defense medal behavior from vanilla Q3 for the game mode Capture The Lolly. It should be awarded for defending the base and the lolly carrier by taking out enemy players/bots near your lolly or near the team member currently carrying the lolly.
- [ ] Apply the Defense medal behavior also to the game mode Big Balloon. It should be awarded for defending a balloon box in your own team color by eliminating opponents in the boxes vicinity.
- [ ] Apply the Defense medal behavior also to the game mode Spray Your Color Team. It should be awarded for defending a team mate carrying min 4 cartridges by eliminating opponents in the team mates vicinity.

**Comment by kai-li-wop** [comment]
With 54fad910843310cbf147c7efc4adca81e89731fc I tried to restore the assist and defend awards form vanilla Q3 but still not taking Team Arena additions into account. I had only time for a quick test but I could see that the PadHero medal (defend) is drawn in CTL bot match. I also recognised that some sounds are somehow mixed now: chat beep is played while jumping for example. This is a strange behaviour which I cannot explain, but I am sure that my changes cause this. I simply don't now where or what I missed. So support is very welcome to help me to finish this enhancement.

**Comment by kai-li-wop** [comment]
The mixed sound problem has disappeared. The behavior of the defense medal seems to be restored. It is awarded for fragging enemy players within 1000 units of the lolly bearer or lolly base.

~~Further research needs to be done to the impressive award, which is still given to players, but without a medal being displayed. This is the player's "hehe2" sound that plays after 2 consecutive frags with the SPLASHER within 3(?) seconds. I can't hear this sound any more and I'm not sure if my changes caused it.~~

**Comment by kai-li-wop** [comment]
With 2f3966c9b64a6e4f4a577583e2121fa35d932698 I enabled the PadHero medal and a team frag bonus in SYC Team. This needs further testing but the following should apply:
- The teammate must carry at least 5 cartridges for a chance at a spray award to enable the PadHero award for the defender
- The teammate's defender must frag the attacker of the teammate within 8 seconds to receive the PadHero award (same like in CTL)
- 2 points are added to the personal score (not to the team score) for each cartridge an opponent was carrying when he got fragged, works from 1+ cartridges (not 5+ cartridges)
- The game now indicates that the player has fragged a cartridge carrier of the opposing team, in which a message is displayed in the message area.

**Comment by kai-li-wop** [comment]
Note to myself and testers: whatever is written in online wikis about the Assist medal in CTF/CTL, there are 2 ways to get it, not 3.

1. if your own team's lolly is not in the home base, you must be returned first. Within 10 seconds, another teammate must score by bringing the opposing lolly to the home base. If he scores in time, you receive the assist medal.
2. if your own team's lolly is not in the home base, you must kill the opposing lolly carrier but must not return the lolly. Someone else from your team can return it. Within 10 seconds, another teammate must score by bringing the opposing flag to the home base. If he scores in time, you get the assist medal.

If there are two teammates involved, one killing the opposing lolly carrier and the other returning the lolly, both will receive the Assist medal as long as a third teammate scores within 10 seconds.

**Comment by kai-li-wop** [comment]
PadHero should work now for all 3 gametypes: CTL, BB and SYC Team

**Comment by 3aTmE** [comment]
Just tried it locally: 

**CTL**

> Both player events works fine! Like stated above _PadHero_ soundfile is currently missing. But shows up correctly.  
> Same with _PadAce._  The correct sound plays when triggered. 

**BB**

> _PadHero_ palyer event triggers fine while defending an Balloon.

**SYC TEAM**

> _PadHero_ event when defending own cartridge carrier works like intended. The "`PlayerName` Has Fragged `TEAM COLOR` Cartridge Carrier" message will only display when the enemy cartridge carrier had 1 or more Cartridges collected.

Yeah, works fine. Only the Soundclip for _PadHero_ is missing :)
