### ISSUE TITLE
Restore and adjust Q3A assist medal as 'WatchPad' in WoP

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#193]
Icon | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_excellent.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_snackattack.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_padstar_blue.png" width="60" /> <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_padstar_red.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_padhero.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_watchpad.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_spraykiller.png" width="60" /> | <img src="https://media.githubusercontent.com/media/PadWorld-Entertainment/worldofpadman/main/wop/gfx.pk3dir/icons/medal_spraygod.png" width="60" />
--- | :---: | :---: | :---: | :---: | :---: | :---: | :---:
Name | Excellent | SnackAttack | PadStar (BLUE/RED) | PadHero | WatchPad | SprayKiller | SprayGod

## Tasks

- [x] Restore the Assist award behavior from vanilla Q3 for the game mode Capture The Lolly. It should be awarded (1) for returning the own lolly, and (2) for killing the opposing lolly carrier if a teammate scores shortly after.
- [x] Apply the Assist award also to the game mode Big Balloon. It should be awarded for helping someone raising a balloon, because it's speeding up the process since WoP 1.5 the more players stand around the balloon. Right now all players raising the same balloon get the PadStar icon shown above their heads. So we need to distinguish who arrived first to raise the balloon and who came later and supported
- ~~Apply the Assist award also to the game mode Spray Your Color Team. It should be awarded for helping someone to achieve SprayKiller or SprayGod by actively giving (throwing) cartridges to that player. So we need to track who gave how many cartridges to another player before scoring SprayKiller or SprayGod afterwards. Like in CTL we could set a 10 seconds counter in which the player who receives the carts must score.~~
- [x] Needs an icon texture plus shader
- [ ] Needs an announcer sound file

Note to myself and testers: whatever is written in online wikis about the Assist medal in CTF/CTL, there are 2 ways to get it:

1. if your own team's lolly is not in the home base, you must be returned first. Within 10 seconds, another teammate must score by bringing the opposing lolly to the home base. If he scores in time, you receive the assist medal.
2. if your own team's lolly is not in the home base, you must kill the opposing lolly carrier but must not return the lolly. Someone else from your team can return it. Within 10 seconds, another teammate must score by bringing the opposing flag to the home base. If he scores in time, you get the assist medal.

If there are two teammates involved, one killing the opposing lolly carrier and the other returning the lolly, both will receive the Assist medal as long as a third teammate scores within 10 seconds.

**Comment by kai-li-wop** [comment]
@mgerhardy: To apply assist medal for BB please have a look at g_trigger.c, search for comment:
"// FIXME: If some players come "later", they will also be calculated for the full time."

We need to distinguish between first player and others coming later.

AddBalloonScores simply gives everyone a PadStar award near the balloon.

**Comment by kai-li-wop** [comment]
e41bf0401750d5ff47174bef87cb3a9e4a0e52f7 should apply the assist medal (PadAce) to Big Balloon. Would be good to test this a little. I could not debug this, but it seems that always the same player receives PadStar, even if he is coming later to raise the balloon.

**Comment by kai-li-wop** [comment]
PadAce (assist) should work in BB now as intended.

**Comment by 3aTmE** [comment]
> PadAce (assist) should work in BB now as intended.

I can confirm this. Just played a round of BB because of a different issue. The Medal triggered just fine! 👍

**Comment by kai-li-wop** [comment]
Some more info on how the Assist award could work also in the game mode Spray Your Color Team:
- It should be awarded for helping someone to achieve SprayKiller or SprayGod
- Therefore the player must actively give (throw) cartridges to that spraying player, not drop it by dying
- To be able to track this every cartridge actively given needs an owner tag and a time tag
- If the sprayer sprays 5 or 8 cartridges in a row and the time tag of every cartridge is not greater than 10(?) seconds after the cart was given, the prior owner receives the assist award PadAce
- If the time tag is greater than 10(?) seconds, time and owner tag is reset to nothing
- If the cartridge receiver again gives the received cartridges to someone else, time and owner tag is reset by that player

**Comment by kai-li-wop** [comment]
```
\g_gametype 10
\devmap wop_jail
\give ammo_spray
\give ammo_spray
\give ammo_spray
\give ammo_spray
\give ammo_spray
```

Drop all cartridges with Backspace or F-key directly to another player. If he scores min 5 cartridges in a row (25 points) he will achieve SprayKiller. So the cartridge giver will receive PadAce award.

**Comment by kai-li-wop** [comment]
Due to unforeseen difficulties and limited capacity, we will not be implementing WatchPad for the SYC team.
