### ISSUE TITLE
Presentation of medals/rewards via the scoreboard

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#194]
Players complain that there is no place to get an overview of the medals already received during a match. For this purpose, they would like to see the scoreboard, where there could be a corresponding display.

## Tasks
- [x] Add a new section below the score table but still within the bg image frame to present the player's medals achieved during a match
- [x] It should list all achieved medal icons during a match, which would be up to six max in SYC Team
- [x] It should not show medal icons, which are not achievable in the current game mode like SprayKiller in a CTL match
- [x] It should show the count of each medal achieved centred on top of the medal icons
- [x] Medal section needs a header texture --> cgs.media.scoreboardMedals

Current status of implementation:

![Image](https://github.com/PadWorld-Entertainment/worldofpadman/assets/44040989/748bd6df-e937-40a0-9fd8-efcdfe43ded0)

**Comment by 3aTmE** [comment]
After playing locally for a few rounds i can confirm that the medals on the scoreboard are showing up correctly! 👍 
(Game modes tested so far: CTL, FFA)

**Comment by kai-li-wop** [comment]
@3aTmE: Can you please test also in other game modes. During testing I sometimes received SnackAttack with a count shown correctly. Randomly the count was 0 after a while and I needed to receive another medal and suddenly the count of SnackAttack was shown correctly again. Seemed to me some random behavior when calling the Scoreboard with Tab within matches. Best would be to test in SYC Team becaus in this game mode you can receive up to 6 different medals (including PadAce which is still not implemented yet).

**Comment by 3aTmE** [comment]
> @3aTmE: Can you please test also in other game modes. During testing I sometimes received SnackAttack with a count shown correctly. Randomly the count was 0 after a while and I needed to receive another medal and suddenly the count of SnackAttack was shown correctly again. Seemed to me some random behavior when calling the Scoreboard with Tab within matches. Best would be to test in SYC Team becaus in this game mode you can receive up to 6 different medals (including PadAce which is still not implemented yet).

I was not able to reproduce your issue with the snack attack, the counter showed always the correct value :)
