### ISSUE TITLE
Project specific documentation

### ISSUE THREAD

**Issue by robo9k** [PadWorld-Entertainment/worldofpadman#23]
>It seems that there should be a project-specific README.md or something that gets people started on the right path instead of the default ioq3 readmes... 

_Originally posted by @rcampbel3 in https://github.com/PadWorld-Entertainment/worldofpadman/issues/4#issuecomment-422451935_

Some things that should be changed from the top of my head:
- [x] `README.md`
- [x] `CONTRIBUTING.md`
- [x] `COPYING.txt` or similar needs to mention proprietary license of World of PADMAN assets (`*.pk3` etc.)
- [x] `SECURITY.md` needs a `@worldofpadman.net` or `@padworld-entertainment.com` email address etc.
- [x] `autoupdater-readme.txt` is unused so far
