### ISSUE TITLE
MAPACK: Todo's Hectic's Workshop

### ISSUE THREAD

**Issue by kai-li-wop** [PadWorld-Entertainment/worldofpadman#342]
Todo's
- [x] merge SYC and BB version in one file
- [x] test/add add this map with/for CTKD and FT
- [x] add pbox_blue model

Fix warnings:
- [x] light at (976 -664 312) has missing target
- [x] teleporter destination (target_position13) in solid
- [x] texture or shader 'textures/pad_floorout/Floor008a' not found
- [x] texture or shader 'textures/pad_glow/Postcard1' not found

No solution possible by now
- separate teams when entering spray room
- teleporter destination (target_print1) in solid
